### GET all teachers
GET http://localhost:8080/api/academia/profesori?page=100&size=10&sort=albdulah

### GET teacher by id
GET http://localhost:8080/api/academia/profesori/10

### POST create new teacher
POST http://localhost:8080/api/academia/profesori
Content-Type: application/json

{
  "nume": "Alibaba",
  "prenume": "Petrica",
  "email": "ciocc@huray.com",
  "gradDidactic": "ASISTENT",
  "tipAsociere": "TITULAR"
}